code:
  include_lists:
    - TODO
    - DOING
    - DONE
    - PLANNING
    - FIXME
    - ARCHIVE
    - HACK
    - CHANGED
    - XXX
    - IDEA
    - NOTE
    - REVIEW
lists:
  - filter: 'dueDate < "${tomorrow at 6AM}" AND list != DONE +dueDate +order'
    hidden: true
    id: sktwi16g7m5skwq80
    name: What's Due?
  - hidden: false
    name: NOTE
    id: sktwi16g7m5skwq81
  - hidden: false
    name: TODO
    id: sktwi16g7m5skwq82
  - hidden: false
    name: DOING
    id: sktwi16g7m5skwq83
  - hidden: false
    ignore: true
    name: DONE
    id: sktwi16g7m5skwq84
  - filter: 'completedDate > "${7 days ago}" -completed'
    hidden: false
    id: sktwi16g7m5skwq85
    name: Recently Completed
  - name: FIXME
    hidden: false
    ignore: false
    id: sktwi16g7m5skwr7u
settings:
  openIn: code
  journalType: New File
  journalPath: backlog
  appendNewCardsTo: my-journal.md
  newCardSyntax: MARKDOWN
  replaceSpacesWith: '-'
  plugins:
    HeaderFooterPlugin:
      afterPrefix: '${!/.md$/.test(relPath) ? ''## **:hammer_and_wrench:** '' : ''''}'
    devMode: false
  journalTemplate: null
  markdownOnly: false
  editorTheme: blackboard
  theme: dark
  useVimKeyBindings: false
  views: []
  name: imdone-obsidian-plugin
  kudosProbability: 0.33
  cards:
    colors: []
    template: |

      <!--
      created:${(new Date()).toISOString()}
      -->
    trackChanges: false
    metaNewLine: true
    addCompletedMeta: true
    addCheckBoxTasks: false
    doneList: DONE
    tokenPrefix: '#'
    taskPrefix: '#'
    tagPrefix: '#'
    metaSep: ':'
    orderMeta: true
    maxLines: 6
    addNewCardsToTop: true
    showTagsAndMeta: true
    defaultList: TODO
    archiveCompleted: true
    archiveFolder: backlog/archive
